# syntax=docker/dockerfile:1.4

FROM golang:1.21 AS builder
WORKDIR /src
ADD . .
RUN --mount=type=cache,target=/root/.cache --mount=type=cache,target=/go/pkg/mod <<eof
  CGO_ENABLED=0 go build -trimpath -ldflags '-w -s' -o /server ./cmd/server
eof

FROM gcr.io/distroless/static:nonroot
LABEL maintainer="Jian Zeng <anonymousknight96@gmail.com>"
COPY --from=builder /server /server
ENTRYPOINT ["/server"]
