name: "Test"
on:
  push: {}
  pull_request: {}
  schedule:
  - cron: "0 0 * * 1" # At 0:00 on Monday
  workflow_dispatch: {}
concurrency:
  group: ci-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true
permissions:
  contents: read
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.17]
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Cache Go Module
      uses: actions/cache@v2
      with:
        # In order:
        # * Module download cache
        # * Build cache (Linux)
        # * Build cache (Mac)
        # * Build cache (Windows)
        path: |
          ~/go/pkg/mod
          ~/.cache/go-build
          ~/Library/Caches/go-build
          %LocalAppData%\go-build
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - name: Test
      run: make test
    - name: Lint
      uses: golangci/golangci-lint-action@v2
      with:
        # use pre-installed Go
        skip-go-installation: true
        # don't cache or restore ~/go/pkg
        skip-pkg-cache: true
